### ISSUE TITLE
Add someone to GitHub

### ISSUE THREAD

**Issue by samuelvenzi** [hyperledger-labs/governance#108]
Please include:

* GitHub ID to add: 
    * https://github.com/andremacedopv
    * https://github.com/mikaellafs
    * https://github.com/lucas-campelo
* Lab to be added to: `cc-tools-maintainers` Team
* Role:
	- Manage
-------
* GitHub ID to add: 
    * https://github.com/jamillepp
    * https://github.com/AlineLermen
* Lab to be added to: `cc-tools-committers` Team
* Role:
	- Write

-------
Extra info: For some reason they were removed from the org (we had them initially as maintainers or committers: https://github.com/hyperledger-labs/governance/issues/28)

**Comment by tkuhrt** [comment]
Please file a pull request against https://github.com/hyperledger-labs/governance/blob/main/config.yaml#L38
