### ISSUE TITLE
Add to GitHub: sophia1ch

### ISSUE THREAD

**Issue by iljabvh** [hyperledger-labs/governance#110]
Please include sophia1ch to the perun lab. She is already in the [MAINTAINERS file](https://github.com/hyperledger-labs/go-perun/blob/main/MAINTAINERS.md) in one of our repos. We will also add her in [this](https://github.com/hyperledger-labs/perun-eth-contracts/pull/40) repository with a [new MAINTAINERS.md file](https://github.com/hyperledger-labs/perun-eth-contracts/blob/e00487e89981a64c522d8ae0b56a34950175696d/MAINTAINERS.md)

* GitHub IDs to add: sophia1ch
* Lab to be added to: perun 
* Role:
	- Write

Best regards,
Ilja

**Comment by ryjones** [comment]
Hi, [please file a PR here](https://github.com/hyperledger-labs/governance/blob/ce676973957faba16221eabcd935152304961b78/config.yaml#L193)

**Comment by iljabvh** [comment]
Thanks, I have made a [PR](https://github.com/hyperledger-labs/governance/pull/111) to update the whole perun and perun-committers teams.
