### ISSUE TITLE
Transfer a repo

### ISSUE THREAD

**Issue by mbwhite** [hyperledger-labs/governance#15]
Please include:

* GitHub repo to transfer:
  https://github.com/ibm-blockchain/microfab
* Lab to be added to: 
 https://github.com/hyperledger-labs/microfab
* Teams with which access: (examples [on GitHub team list](https://github.com/orgs/hyperledger-labs/teams))
	* Team name:
	* Role:
		- Read
		- Triage
		- Write
		- Manage
		- Admin    mbwhite / daveenyeart / jamestaylor

**Comment by ryjones** [comment]
OK @mbwhite transfer the repo to me

**Comment by mbwhite** [comment]
@ryjones  on it's way!  I've had to transfer it to myself first, and then to you

**Comment by ryjones** [comment]
https://github.com/hyperledger-labs/microfab
