### ISSUE TITLE
Create repo for ibm-blockchain/ansible-collection to be a new lab

### ISSUE THREAD

**Issue by mbwhite** [hyperledger-labs/governance#16]
The PR to approve a new labs has been merged see https://github.com/hyperledger-labs/hyperledger-labs.github.io/pull/227

The existing repo is https://github.com/ibm-blockchain/ansible-collection/ - however, I'd like that to remain where it is and create the hyperledger labs repo by forking that.  (having considered the implications a bit more from my comment in the PR a direct transfer will cause issues)

Reason is that there is IBM/IBM Blockchain Platform code that needs to stay available IBM side, but will be removed in the lab.

If we can fork it, the original can stay and I can then cleanup the labs repo.

Hope that makes sense!

**Comment by ryjones** [comment]
[here you go!](https://github.com/hyperledger-labs/fabric-ansible-collection)
