### ISSUE TITLE
Create a New Repo perun-rs for the perun lab

### ISSUE THREAD

**Issue by choeppler** [hyperledger-labs/governance#17]
The perun team has been working on a rust implementation of the [go-perun](https://github.com/hyperledger-labs/go-perun) library for embedded devices, which we'd like to add to the labs project. Could you please create a perun-rs repo and add add this to the labs project? Thank you!

* GitHub repo to add: https://github.com/hyperledger-labs/perun-rs
* Associated lab proposal: [original lab proposal](https://github.com/hyperledger-labs/hyperledger-labs.github.io/blob/main/labs/perun.md)
* Lab to be added to: perun

**Comment by ryjones** [comment]
[here you go](https://github.com/hyperledger-labs/perun-rs)!
