### ISSUE TITLE
Add Jens to GitHub

### ISSUE THREAD

**Issue by choeppler** [hyperledger-labs/governance#18]
Please add Jens, a Perun developer, to the hyperledger-labs Org

* GitHub ID to add:  DragonDev1906
* Lab to be added to: perun
* Team to be added to @hyperledger-labs/perun-committers 
* Role:
	- Write

**Comment by ryjones** [comment]
Invite sent! @dragondev1906, [please visit the page](https://github.com/hyperledger-labs) to accept the invite
