### ISSUE TITLE
Create a New Repo - learning-tokens

### ISSUE THREAD

**Issue by tkuhrt** [hyperledger-labs/governance#2]
Please include:

* GitHub repo to add: learning-tokens
* Associated lab proposal: hyperledger-labs/hyperledger-labs.github.io#211

**Comment by ryjones** [comment]
- [ ] Create Repo: https://github.com/hyperledger-labs/learning-tokens
- [ ] Create team: https://github.com/orgs/hyperledger-labs/teams/learning-tokens-maintainers/members
- [ ] Invite maintainers to team and org
