### ISSUE TITLE
Add these people as Cardea project maintainers

### ISSUE THREAD

**Issue by Eldersonar** [hyperledger-labs/governance#20]
## Maintainers

- [AmmonBurgi](https://github.com/AmmonBurgi), Cardea, roles: read, write
- [Eldersonar](https://github.com/Eldersonar), Cardea, roles: read, write
- [JamesKEbert](https://github.com/JamesKEbert), Cardea, roles: read, write
- [KeelaShatzkin](https://github.com/KeelaShatzkin), Cardea, roles: read, write, manage
- [lynnbendixsen](https://github.com/lynnbendixsen), Cardea, roles: read, manage, write, admin
- [Megan-Olsen](https://github.com/Megan-Olsen), Cardea, roles: read, write
- [mikekebert](https://github.com/mikekebert), Cardea, roles: read, write, manage
- [reflectivedevelopment](https://github.com/reflectivedevelopment), Cardea, roles: read, write, manage

**Comment by ryjones** [comment]
@Eldersonar invites sent. Please add the required MAINTAINERS.md files to the repos.
