### ISSUE TITLE
Transfer a repo

### ISSUE THREAD

**Issue by tkuhrt** [hyperledger-labs/governance#21]
Related to newly approved lab [hyperledger-labs.github.io#238
](https://github.com/hyperledger-labs/hyperledger-labs.github.io/pull/238)

Please include:

* GitHub repo to transfer: https://github.com/AdharaProjects/Crosschain-Interop
* Lab to be added to: This will become the new lab `harmonia`
* Teams with which access: This will be a new team
	* Team name: harmonia-committers
	* Role:
		- Manage
        * Team members:
                - https://github.com/coeniebeyers - Adhara
                - https://github.com/eierina - R3
                - https://github.com/fenryka - R3
                - https://github.com/gendal - R3
                - https://github.com/MarkOldfield - R3
                - https://github.com/MicheleCullinan - Adhara
                - https://github.com/mkrielza - Adhara
                - https://github.com/petermunnings - Adhara
                - https://github.com/r3domfox - R3

**Comment by ryjones** [comment]
The team is created; once the repo is transferred, I will make the change

**Comment by ryjones** [comment]
@petermunnings you don't need to wait on the PR merge - it will come over. [go here](https://github.com/AdharaProjects/Crosschain-Interop/transfer) and transfer it to me, @ryjones.

**Comment by petermunnings** [comment]
Done:  "Repository transfer to ryjones requested"
