### ISSUE TITLE
Create a New Repo

### ISSUE THREAD

**Issue by cmickeyb** [hyperledger-labs/governance#23]
We would like to create a second repository for the private data objects lab. The second repository would include contracts and applications that build on the pdo infrastructure.

We would like the repository to be https://github.com/hyperledger-labs/pdo-contracts.

The original proposal for PDO is here: https://github.com/hyperledger-labs/hyperledger-labs.github.io/blob/main/labs/private-data-objects.md.

PDO has been successful in influencing several other hyperledger projects (Avalon, Fabric Private Chaincode).

**Comment by ryjones** [comment]
[here you go!](https://github.com/hyperledger-labs/pdo-contracts) Please add a MAINTAINERS.md file
