### ISSUE TITLE
AlfonsoGovela

### ISSUE THREAD

**Issue by AlfonsoGovela** [hyperledger-labs/governance#25]
Please include:

* GitHub ID to add: AlfonsoGovela
* Lab to be added to: 
* Role:
	- Read 
	- Write
	- Manage
	- Admin

**Comment by ryjones** [comment]
@AlfonsoGovela there is a pending invite to add you to learning-tokens

**Comment by AlfonsoGovela** [comment]
Thank you for reminding me.
Just asked for it. 

Best regards,

Alfonso
