### ISSUE TITLE
Transfer a repo

### ISSUE THREAD

**Issue by tkuhrt** [hyperledger-labs/governance#27]
Please include:

* GitHub repo to transfer: https://github.com/input-output-hk/atala-prism-building-blocks
* Lab to be added to: https://github.com/hyperledger-labs/hyperledger-labs.github.io/pull/239
* Teams with which access: (examples [on GitHub team list](https://github.com/orgs/hyperledger-labs/teams))
	* Team name:  open-enterprise-agent-maintainers (NEW)
	* Role:
		- Maintain
	* Members:
	        -  https://github.com/bsandmann
	        -  https://github.com/patlo-iog
	        -  https://github.com/davidpoltorak-io
	        -  https://github.com/antonbaliasnikov
	        -  https://github.com/yshyn-iohk

	* Team name: open-enterprise-agent-committers (NEW)
	* Role:
		- Write
	* Members
	        -  https://github.com/patlo-iog
	        -  https://github.com/davidpoltorak-io
	        -  https://github.com/antonbaliasnikov
	        -  https://github.com/FabioPinheiro
	        -  https://github.com/mineme0110
	        -  https://github.com/bvoiturier
	        -  https://github.com/yshyn-iohk
	        -  https://github.com/CryptoKnightIOG
	        -  https://github.com/shotexa
	        -  https://github.com/goncalo-frade-iohk
	        -  https://github.com/lohanspies

**Comment by ryjones** [comment]
teams created.

**Comment by antonbaliasnikov** [comment]
Hey @ryjones , @tkuhrt !

Could we, please, add the following additional members to `open-enterprise-agent-committers`:

https://github.com/BS-IO
https://github.com/hamada147
https://github.com/amagyar-iohk
https://github.com/petevielhaber
https://github.com/cristianIOHK
https://github.com/curtis-h
https://github.com/elribonazo
https://github.com/essbante-io
https://github.com/EzequielPostan
https://github.com/dorultan
https://github.com/womfoo
https://github.com/mkbreuningIOHK
https://github.com/milosbackonja
https://github.com/milosh86

Thank you!

**Comment by ryjones** [comment]
@antonbaliasnikov invites sent!

**Comment by antonbaliasnikov** [comment]
Hey @ryjones !

Thanks. Almost everybody achieved invitations, except for https://github.com/EzequielPostan .

Could you, please, check and send the invitation once again if not active? Thank you!
