### ISSUE TITLE
Transfer a repo

### ISSUE THREAD

**Issue by samuelvenzi** [hyperledger-labs/governance#28]
## GitHub repo to transfer:

* [https://github.com/GoLedgerDev/cc-tools](https://github.com/GoLedgerDev/cc-tools)
* [https://github.com/GoLedgerDev/cc-tools-demo](https://github.com/GoLedgerDev/cc-tools-demo)
* [https://github.com/GoLedgerDev/cc-tools-doc](https://github.com/GoLedgerDev/cc-tools-doc)

## Lab to be added to: 
* https://github.com/hyperledger-labs/hyperledger-labs.github.io/pull/248

### Team name: cc-tools-admin
* Role:
	- Admin
* Members:
	- [https://github.com/goledger](https://github.com/goledger)
	- [https://github.com/samuelvenzi](https://github.com/samuelvenzi)
### Team name: cc-tools-maintainers
* Role:
	- Maintain
* Members:
	- [https://github.com/andremacedopv](https://github.com/andremacedopv)
	- [https://github.com/mikaellafs](https://github.com/mikaellafs)
	- [https://github.com/lucas-campelo](https://github.com/lucas-campelo)
### Team name: cc-tools-committers
* Role:
	- Write
* Members:
	- [https://github.com/AlineLermen](https://github.com/AlineLermen)
	- [https://github.com/jamillepp](https://github.com/jamillepp)

**Comment by ryjones** [comment]
@samuelvenzi transfer the repos to me, `ryjones`

**Comment by ryjones** [comment]
@samuelvenzi invites sent

**Comment by samuelvenzi** [comment]
@ryjones `Repository transfer to ryjones requested` for all 3 repos

**Comment by ryjones** [comment]
done!
