### ISSUE TITLE
Add “peacekeeper" to GitHub Org as part of the did:webs maintainers team

### ISSUE THREAD

**Issue by swcurran** [hyperledger-labs/governance#30]
Please include:

* GitHub ID to add: peacekeeper
* Lab to be added to: [did-webs-resolver-maintainers/members](https://github.com/orgs/hyperledger-labs/teams/did-webs-resolver-maintainers/members)
* Role:
	- Admin, or
	- Maintainer

FYI: @peacekeeper

**Comment by tkuhrt** [comment]
Invite sent to @peacekeeper
