### ISSUE TITLE
Add a new maintainer to the Harmonia repository 

### ISSUE THREAD

**Issue by petermunnings** [hyperledger-labs/governance#32]
Hi please can we add Michéle Cullinan to the list of maintainers on the Harmonia list of committers (https://github.com/orgs/hyperledger-labs/teams/harmonia-committers).

Her Github handle is MicheleCullinan

She was on the original list, so it appears to have been an oversight https://github.com/hyperledger-labs/harmonia#initial-committers
Unless I am missing something

**Comment by ryjones** [comment]
Invite sent!

**Comment by ryjones** [comment]
@petermunnings  in the future please use the template, as it adds assignees. That's why I missed this!
