### ISSUE TITLE
Update request to Harmonia committers

### ISSUE THREAD

**Issue by eierina** [hyperledger-labs/governance#33]
Please kindly update the Harmonia committers list https://github.com/orgs/hyperledger-labs/teams/harmonia-committers as follows.

Add:

GitHub ID to add: @jmacmahonr3  -  James Mac Mahon from R3
GitHub ID to add: @ILoomans  -  Ignace Loomans from R3

Remove:

GitHub ID to remove: @fenryka  -  Katelyn Baker formerly R3

**Comment by ryjones** [comment]
@eierina done!

**Comment by ryjones** [comment]
@eierina in the future please use the template, as it adds assignees. That's why I missed this!
