### ISSUE TITLE
Add Ilja to GitHub

### ISSUE THREAD

**Issue by iljabvh** [hyperledger-labs/governance#37]
Please add Ilja, that's me, Perun technical lead, to hyperledger-labs.

* GitHub ID to add: iljabvh
* Lab to be added to: perun
* Role:
	- Write

Tagging @choeppler @DragonDev1906 @rmbrt for verification of this request.

**Comment by ryjones** [comment]
Hi, @iljabvh , please make sure the maintainers.md files are updated in all repos. https://github.com/hyperledger-labs/perun-node/blob/develop/MAINTAINERS.md for instance

**Comment by iljabvh** [comment]
> Hi, @iljabvh , please make sure the maintainers.md files are updated in all repos. https://github.com/hyperledger-labs/perun-node/blob/develop/MAINTAINERS.md for instance

Currently we have NOTICE files in which maintainers are listed, I am listed there as well, see https://github.com/hyperledger-labs/go-perun/blob/main/NOTICE. But of course I am going to include MAINTAINERS.md as well then, it is my responsibility. First i need write access though :)

**Comment by ryjones** [comment]
invite sent!
