### ISSUE TITLE
Create a New Repo to make Solang available on Brew

### ISSUE THREAD

**Issue by LucasSte** [hyperledger-labs/governance#4]
Please include:

* GitHub repo to add: https://github.com/hyperledger-labs/homebrew-solang
* Associated lab proposal: See description below
* Lab to be added to: Solang
-------------------------

Solang is available to download via binaries in our release pages on Github. After attending a blockchain conference from Solana, @seanyoung and I noticed that having to download binaries, excluding them from MacOS quarantine and setting up path variables is too burdensome for developers. We want to make Solang available on Brew to streamline this.

We opened [a pull request](https://github.com/Homebrew/homebrew-core/pull/105138) on brew-core repository to include our formula in Brew. Reviewers were not happy with our compilation, because we need to link Solang against Solana's LLVM fork, which contains changes that are not upstreamed to LLVM official repository. As per reviewers suggestions, we should maintain a private tap.

According to [Brew documentation](https://docs.brew.sh/Taps), we should have a repository with the syntax `https://github.com/<user>/homebrew-<repo>` to enable users to install our binary using the command `brew install user/repo/formula`. In other words, maintaining a `solang.rb` in `https://github.com/hyperledger-labs/homebrew-solang` allows us to install Solang with `brew install hyperledger-labs/solang/solang` or with the following commands:

```
# Tapping the repo
brew tap hyperledger-labs/solang
# Installing!
brew install solang
```

**Comment by ryjones** [comment]
[Happy hacking!](https://github.com/hyperledger-labs/homebrew-solang)
