### ISSUE TITLE
Transfer a repo - acapycontroller

### ISSUE THREAD

**Issue by tkuhrt** [hyperledger-labs/governance#42]
Please include:

* GitHub repo to transfer: https://github.com/OneOf-Inc/acapycontroller
* Lab to be added to: https://github.com/hyperledger-labs/hyperledger-labs.github.io/pull/259
* Teams with which access: (examples [on GitHub team list](https://github.com/orgs/hyperledger-labs/teams))
	* Team name: aries-agent-controller-maintainers
	* Role:
		- Write
	* This is a new team and should have the initial committers added to it

@monar24 : You will need to initiate the transfer of this repo to @ryjones or myself @tkuhrt so that we may move it to the hyperledger-labs organization.

**Comment by tkuhrt** [comment]
https://github.com/hyperledger-labs/aries-agent-controller

**Comment by tkuhrt** [comment]
Invites also sent to the maintainers.

**Comment by ryjones** [comment]
please add a `MAINTAINERS.md` file as well
