### ISSUE TITLE
Add sophia1ch and NhoxxKienn to perun Lab

### ISSUE THREAD

**Issue by iljabvh** [hyperledger-labs/governance#43]
Please include NhoxxKienn and sophia1ch to the perun lab. They are already in the [MAINTAINERS file](https://github.com/hyperledger-labs/go-perun/blob/main/MAINTAINERS.md) in one of our repos.

* GitHub IDs to add: NhoxxKienn, sophia1ch
* Lab to be added to: perun 
* Role:
	- Write

**Comment by ryjones** [comment]
invites sent. I removed some emeritus folks, and missed that matthiasgeihs and manoranjith were maintainers on other repos. I've re-invited them
