### ISSUE TITLE
Transfer a repo

### ISSUE THREAD

**Issue by ahmed82** [hyperledger-labs/governance#44]
Please include:

* GitHub repo to transfer: https://github.com/BDLS-bft/fabric
* Lab to be added to: https://github.com/hyperledger-labs/bdls
* Teams with which access: (examples [on GitHub team list](https://github.com/orgs/hyperledger-labs/teams))
	* Team name: unfound, might be deleted during archive process 
	* Role:
		- Read
		- Triage
		- Write
		- Manage
		- Admin

**Comment by ryjones** [comment]
hi, @ahmed82 . I am not an owner of the repo and I do not have the permissions to transfer the repo. please make me either an org owner, or transfer the repo to my account `ryjones` and I will put it in the right place.

**Comment by ryjones** [comment]
@ahmed82 I also need an up-to-date maintainers.md file for your repo :)

**Comment by ahmed82** [comment]
The invite updated to org owner, also the updated Maintainers list if it is ok to have two groups as below.

**Admin Maintainers**

| Name | GitHub | email | 
|-------------------------|--------|------
| Ahmed Al Salih        | ahmed82 |  <a.alsalih2@gmail.com>

**contributor Maintainers**

| Name | GitHub | email | 
|-------------------------|--------|------
| Ahmed Al Salih        | ahmed82 |  <a.alsalih2@gmail.com>
| Aditya Singh          | sadityakumar9211 |  <sadityakumar9211@gmail.com>
| Yongge Wang            | yonggewang |  <yongge.wang@charlotte.edu>

**Comment by ryjones** [comment]
OK, I think this is set up. lmk!

**Comment by ahmed82** [comment]
All looks good for my ID. 
I will check for other members (Aditya and Dr. Yongge)
Thank you.
