### ISSUE TITLE
Transfer a repo SmartBFT-Go consensus

### ISSUE THREAD

**Issue by pfi79** [hyperledger-labs/governance#45]
* GitHub repo to transfer: https://github.com/SmartBFT-Go/consensus
* Lab to be added to: https://github.com/hyperledger-labs/smart-bft
* Teams with which access: This will be a new team
	* Team name: smartbft-team
	* Role:
		- Read
		- Triage
		- Write
		- Manage
		- Admin
                     - https://github.com/yacovm
                     - https://github.com/HagarMeir
                     - https://github.com/C0rWin
                     - https://github.com/tock-ibm
                     - https://github.com/pfi79

**Comment by pfi79** [comment]
@C0rWin FYI

**Comment by ryjones** [comment]
@pfi79 go to [repo, settings](https://github.com/SmartBFT-Go/consensus/settings), transfer repo (at the bottom), transfer to me, `ryjones`

**Comment by C0rWin** [comment]
@ryjones we are hitting the following message: `You can only transfer a repository from an organization to yourself at this time` do I need to take a personal ownership before transferring to you? 

IMO, we can get you into organization, transfer within it to you and then you can handle however it's appropriate. wdyt?

**Comment by pfi79** [comment]
> @ryjones we are hitting the following message: `You can only transfer a repository from an organization to yourself at this time` do I need to take a personal ownership before transferring to you?
> 
> IMO, we can get you into organization, transfer within it to you and then you can handle however it's appropriate. wdyt?

OR the following message: `pfi79 already has a repository in the SmartBFT-Go/consensus network`

**Comment by ryjones** [comment]
@pfi79 add me as an org owner over there

**Comment by pfi79** [comment]
> @pfi79 add me as an org owner over there

![IMG_20240313_155955_778.jpg](https://github.com/hyperledger-labs/governance/assets/7284783/466d4677-390c-462a-8c2f-a899de7a7712)

**Comment by ryjones** [comment]
@pfi79 weird - I didn't get a notification

**Comment by ryjones** [comment]
[all good to go!](https://github.com/hyperledger-labs/SmartBFT)
