### ISSUE TITLE
Create a New Repo - sunyar-fabric

### ISSUE THREAD

**Issue by tkuhrt** [hyperledger-labs/governance#5]
Please include:

* GitHub repo to add: sunyar-fabric
* Associated lab proposal: hyperledger-labs/hyperledger-labs.github.io#216

**Comment by ryjones** [comment]
@tkuhrt is this a transfer or creation? The proposal has a repo attached

**Comment by ryjones** [comment]
[repo created!](https://github.com/hyperledger-labs/sunyar-fabric)
