### ISSUE TITLE
Reserve the Hyperledger prefix in nuget

### ISSUE THREAD

**Issue by jt-nti** [hyperledger-labs/governance#67]
It looks like there are a few [Hyperledger packages in nuget](https://www.nuget.org/packages?q=Hyperledger) and there's a new issue/PR to add C# namespaces to the Fabric protos — hyperledger/fabric-protos#227 — so it would be great to reserve the Hyperledger prefix if possible

https://learn.microsoft.com/en-gb/nuget/nuget-org/id-prefix-reservation

Thanks

**Comment by ryjones** [comment]
I've sent an email to make this happen

**Comment by ryjones** [comment]
Done
