### ISSUE TITLE
Transfer a repo - BDLS lab

### ISSUE THREAD

**Issue by knagware9** [hyperledger-labs/governance#8]
Please include: 

* GitHub repo to transfer: https://github.com/yonggewang/bdls
* Lab to be added to:  https://github.com/hyperledger-labs/
* Teams with which access: (examples [on GitHub team list](https://github.com/orgs/hyperledger-labs/teams))
	* Team name:  https://github.com/ahmed82
	* Role:
		- Read
		- Triage
		- Write
		- Manage
		- Admin

**Comment by knagware9** [comment]
here is the lab approval - https://github.com/hyperledger-labs/hyperledger-labs.github.io/pull/197

**Comment by knagware9** [comment]
https://github.com/hyperledger-labs/hyperledger-labs.github.io/pull/197/files/bdd6d0be78f2b63891793fe29abbad508248f9cc

**Comment by ryjones** [comment]
OK, @ahmed82, transfer the repo to me, @ryjones

**Comment by ahmed82** [comment]
> OK, @ahmed82, transfer the repo to me, @ryjones
Thank you, Ry, The bdls repository on the way.
```
Transfer ownership
This repository is being transferred to @ryjones.
```
