### ISSUE TITLE
Add someone to GitHub

### ISSUE THREAD

**Issue by swaptr** [hyperledger-labs/governance#86]
Please include:

* GitHub ID to add: @swaptr
* Lab to be added to: aifaq-maintainers
* Role:
	- Write
	- Manage

**Comment by nidhi-singh02** [comment]
Thank you @swaptr! Can we get confirmation from the existing maintainer please.

**Comment by gcapuzzi** [comment]
Hello @nidhi-singh02 yes I confirm @swaptr as maintainer, thank you
