### ISSUE TITLE
Transfer a repo

### ISSUE THREAD

**Issue by arsulegai** [hyperledger-labs/governance#89]
Please include:

* GitHub repo to transfer: https://github.com/arsulegai/fabric-debugger
* Lab to be added to: fabric-debugger
* Teams with which access: (examples [on GitHub team list](https://github.com/orgs/hyperledger-labs/teams))
	* Team name: fabric-debugger-committers
	* Members: @arsulegai , @kentydotcom , @technomad01 , @urgetolearn , @varshapichandi30 
	* Role:
		- Read
		- Triage
		- Write
	* Team name: fabric-debugger-admins
	* Members: @arsulegai
	* Role:
		- Manage
		- Admin

**Comment by arsulegai** [comment]
@ryjones I sent a request to transfer the repository to your account.

**Comment by ryjones** [comment]
done
