### ISSUE TITLE
Add Digital Asset automation user to GitHub

### ISSUE THREAD

**Issue by isegall-da** [hyperledger-labs/governance#99]
Sorry, one more user please. This is a service account used by our automation, which will update the periodic dumps, until we switch our active development over to Splice

* GitHub ID to add: 
  * canton-network-da
* Lab to be added to: 
  * Splice
* Role:
	- Manage (please add to splice-contributors)

Thanks

**Comment by ryjones** [comment]
@isegall-da feel free to file a PR and I will approve

**Comment by ryjones** [comment]
fixed by #100
